/**
 * SeaBound Icon Specification
 *
 * This is the source-of-truth for all game icons. Add/remove/edit entries here,
 * then sync to your GameProject via the API or MCP tools.
 *
 * The spec is intentionally separate from generation state — this file describes
 * WHAT you need, while the GameProject manifest in R2 tracks what you HAVE.
 */

import type { GameIconSpec, GameStyleGuide } from "./types.js";

export const SEABOUND_STYLE: GameStyleGuide = {
  approach: "Painterly pixel art — chunky but expressive, 2-3px outlines",
  resolution: "64×64 native, rendered at 32×32 in-game (retina-ready)",
  paletteConstraints: [
    "Dark teal/ocean background (#0c1a1a to #132626) — icons must pop against this",
    "Warm sand/amber highlights (#f0a050, #c8b090) for organic materials",
    "Cool blue-greens (#50b0d0, #38bdf8) for water/maritime items",
    "Muted grey-blue (#a0a8b8) for stone items",
    "Lush greens (#7bc67b, #4ade80) for plant/bamboo items",
    "Fire oranges/reds (#f0a050, #e05030) for cooked/fire items",
    "All icons should have slight warm ambient light as if lit by tropical sun or campfire",
  ],
  composition: [
    "Single object, centered, filling ~80% of the frame",
    "Slight 3/4 top-down perspective (like looking at items on the ground)",
    "Subtle drop shadow on bottom edge for depth",
    "No background — transparent PNG with optional subtle glow matching phase color",
  ],
  consistency: [
    "Same lighting direction (top-left) across all icons",
    "Same outline weight (2-3px at 64×64)",
    "Natural, weathered, handmade feel — nothing looks factory-produced",
    "Tropical island color temperature — warm, slightly sun-bleached",
  ],
  phaseTinting: {
    bare_hands: "Sandy, muted tones (#c8b090). Raw, unprocessed look.",
    bamboo: "Green-tinted (#7bc67b). Fresh-cut, fibrous textures.",
    fire: "Warm amber/orange (#f0a050). Charred edges, smoke wisps.",
    stone: "Cool grey-blue (#a0a8b8). Sharp edges, flaked surfaces.",
    maritime: "Ocean blue-cyan (#50b0d0). Weathered wood, salt-bleached.",
  },
};

export const SEABOUND_ICONS: GameIconSpec[] = [
  // ── Coconut chain ─────────────────────────────────────────────────
  {
    id: "coconut",
    object: "Whole brown coconut",
    description: "Mature coconut with rough brown husk, fibrous texture visible. Slight green tinge at the stem end.",
    use: "Inventory, gathering rewards, recipe inputs",
    theme: "bare_hands",
    category: "fruit",
    chain: "coconut",
    chainRole: "base",
    size: 64,
    tags: ["phase0", "beach", "organic", "gatherable"],
  },
  {
    id: "coconut_husk",
    object: "Torn coconut husk fibers",
    description: "Ragged chunk of brown coconut husk, fibrous strands pulling apart. Same coconut color/texture as coconut icon but clearly torn open.",
    use: "Inventory, crafting intermediate",
    theme: "bare_hands",
    category: "fiber",
    chain: "coconut",
    chainRole: "derived",
    chainNote: "Same coconut but ripped apart — show the fibrous interior",
    size: 64,
    tags: ["phase0", "beach", "organic", "craftable"],
  },

  // ── Driftwood / Wood chain ────────────────────────────────────────
  {
    id: "driftwood_branch",
    object: "Sun-bleached driftwood stick",
    description: "Pale, smooth driftwood branch with knots. Salt-bleached grey-tan color, slightly curved.",
    use: "Inventory, basic crafting ingredient",
    theme: "bare_hands",
    category: "wood",
    chain: "wood",
    chainRole: "base",
    size: 64,
    tags: ["phase0", "beach", "organic", "gatherable"],
  },
  {
    id: "large_log",
    object: "Thick fallen tree trunk section",
    description: "Large dark-barked log, freshly cut end visible with rings. Much bigger and darker than driftwood — tropical hardwood.",
    use: "Inventory, dugout canoe construction",
    theme: "bamboo",
    category: "wood",
    chain: "wood_heavy",
    chainRole: "base",
    size: 64,
    tags: ["phase1", "jungle", "organic"],
  },
  {
    id: "charred_log",
    object: "Fire-hollowed log",
    description: "Same large log but with blackened, charred interior hollow. Orange ember glow at the charred edges. Exterior bark still visible.",
    use: "Inventory, dugout canoe intermediate",
    theme: "fire",
    category: "wood",
    chain: "wood_heavy",
    chainRole: "derived",
    chainNote: "Same log as large_log but interior burned black with ember glow",
    size: 64,
    tags: ["phase1b", "fire", "crafted"],
  },
  {
    id: "shaped_hull",
    object: "Carved canoe hull",
    description: "Smooth hollowed-out log shaped into a boat hull. Tool marks visible. Same wood tone as large_log but refined.",
    use: "Inventory, dugout canoe intermediate",
    theme: "maritime",
    category: "wood",
    chain: "wood_heavy",
    chainRole: "derived",
    chainNote: "Same log, now scraped smooth and shaped into a hull form",
    size: 64,
    tags: ["maritime", "crafted"],
  },

  // ── Stone chain ───────────────────────────────────────────────────
  {
    id: "flat_stone",
    object: "Smooth flat river stone",
    description: "Flat, rounded grey stone with subtle warm tones. Smooth from water erosion. Palm-sized.",
    use: "Inventory, basic tool crafting",
    theme: "bare_hands",
    category: "stone",
    chain: "stone_basic",
    chainRole: "base",
    size: 64,
    tags: ["phase0", "rocky_shore", "mineral", "gatherable"],
  },
  {
    id: "chert",
    object: "Angular chert nodule",
    description: "Brownish-grey flint-like stone with waxy sheen. Conchoidal fracture surface visible. Slightly translucent at thin edges.",
    use: "Inventory, knapping input",
    theme: "stone",
    category: "stone",
    chain: "stone_knapped",
    chainRole: "base",
    size: 64,
    tags: ["phase2", "rocky_shore", "mineral"],
  },
  {
    id: "stone_flake",
    object: "Knapped stone flake",
    description: "Thin, sharp-edged stone flake with visible bulb of percussion. Same chert color as chert icon. Concentric ripple marks on surface.",
    use: "Inventory, blade crafting intermediate",
    theme: "stone",
    category: "stone",
    chain: "stone_knapped",
    chainRole: "derived",
    chainNote: "A sharp flake struck from the chert nodule — same color, thinner, sharper",
    size: 64,
    tags: ["phase2", "crafted", "mineral"],
  },
  {
    id: "stone_blade",
    object: "Long narrow stone blade",
    description: "Elongated pressure-flaked blade, razor-sharp edges with fine serrations. Same chert material. Longer and more refined than stone_flake.",
    use: "Inventory, advanced tool crafting",
    theme: "stone",
    category: "stone",
    chain: "stone_knapped",
    chainRole: "derived",
    chainNote: "A refined, elongated version of the stone_flake — same material, more worked",
    size: 64,
    tags: ["phase2", "crafted", "mineral"],
  },
  {
    id: "obsidian",
    object: "Obsidian chunk",
    description: "Glossy black volcanic glass with sharp edges. Deep purple-black with glassy reflections. Dramatically different from chert.",
    use: "Inventory, advanced blade crafting",
    theme: "stone",
    category: "stone",
    chain: "obsidian",
    chainRole: "base",
    size: 64,
    tags: ["phase2", "nearby_island", "mineral", "rare"],
  },

  // ── Palm / Plant chain ────────────────────────────────────────────
  {
    id: "palm_frond",
    object: "Large palm leaf",
    description: "Single bright green palm frond with visible midrib and leaflets. Fresh, vibrant green.",
    use: "Inventory, building/weaving input",
    theme: "bare_hands",
    category: "plant",
    chain: "palm",
    chainRole: "base",
    size: 64,
    tags: ["phase0", "coconut_grove", "organic", "gatherable"],
  },
  {
    id: "dry_grass",
    object: "Bundle of dried grass",
    description: "Handful of golden-brown dried grass blades, tied loosely. Sun-bleached straw color.",
    use: "Inventory, fire-starting tinder",
    theme: "bare_hands",
    category: "plant",
    chain: null,
    chainRole: "standalone",
    size: 64,
    tags: ["phase0", "rocky_shore", "organic", "gatherable"],
  },

  // ── Fiber chain ───────────────────────────────────────────────────
  {
    id: "rough_fiber",
    object: "Coarse plant fibers",
    description: "Loose tangle of coarse brown-green fibers, rough and unprocessed. Stringy, irregular strands.",
    use: "Inventory, fiber processing start",
    theme: "bamboo",
    category: "fiber",
    chain: "fiber",
    chainRole: "base",
    size: 64,
    tags: ["phase1", "organic", "craftable"],
  },
  {
    id: "dried_fiber",
    object: "Dried plant fibers",
    description: "Same fibers as rough_fiber but now pale tan, straighter, and stiffer. Clearly dried out and more uniform.",
    use: "Inventory, cordage intermediate",
    theme: "bamboo",
    category: "fiber",
    chain: "fiber",
    chainRole: "derived",
    chainNote: "Same fibers, lighter color, straighter — dried version of rough_fiber",
    size: 64,
    tags: ["phase1", "organic", "craftable"],
  },
  {
    id: "cordage",
    object: "Twisted rope/twine",
    description: "Tightly twisted two-ply cord, same tan fiber material. Neat spiral twist pattern. Coiled in a small loop.",
    use: "Inventory, key crafting ingredient in many recipes",
    theme: "bamboo",
    category: "fiber",
    chain: "fiber",
    chainRole: "derived",
    chainNote: "The dried fibers now twisted into cord — same color, twisted structure",
    size: 64,
    tags: ["phase1", "organic", "craftable", "staple"],
  },

  // ── Fish chain ────────────────────────────────────────────────────
  {
    id: "small_fish",
    object: "Small tropical reef fish",
    description: "A small silvery-blue tropical fish with yellow accents. Alive-looking, slight curve as if just caught. Specific species: a small wrasse or damselfish.",
    use: "Inventory, food, cooking input",
    theme: "bare_hands",
    category: "fish",
    chain: "small_fish",
    chainRole: "base",
    size: 64,
    tags: ["phase0", "beach", "food_raw", "gatherable"],
  },
  {
    id: "cooked_fish",
    object: "Cooked small fish on a leaf",
    description: "The SAME small fish species as small_fish, now golden-brown and grilled. Sitting on a green leaf. Char marks, slight steam wisp.",
    use: "Inventory, food, expedition fuel",
    theme: "fire",
    category: "fish",
    chain: "small_fish",
    chainRole: "derived",
    chainNote: "Same fish species, now cooked golden-brown with char marks and steam",
    size: 64,
    tags: ["phase1b", "food_cooked", "fire"],
  },
  {
    id: "large_fish",
    object: "Large game fish",
    description: "A substantial silvery fish — a trevally or small tuna. Clearly bigger than small_fish. Muscular body, forked tail.",
    use: "Inventory, premium food, cooking input",
    theme: "bare_hands",
    category: "fish",
    chain: "large_fish",
    chainRole: "base",
    size: 64,
    tags: ["phase1", "food_raw"],
  },
  {
    id: "cooked_large_fish",
    object: "Cooked large fish",
    description: "The SAME large fish species, grilled whole on a banana leaf. Golden crust, steam rising. Bigger portion than cooked_fish.",
    use: "Inventory, premium food",
    theme: "fire",
    category: "fish",
    chain: "large_fish",
    chainRole: "derived",
    chainNote: "Same fish species as large_fish, cooked — bigger than cooked_fish",
    size: 64,
    tags: ["phase1b", "food_cooked", "fire"],
  },

  // ── Crab chain ────────────────────────────────────────────────────
  {
    id: "crab",
    object: "Small shore crab",
    description: "A reddish-brown shore crab with claws raised. Compact body, 8 legs visible. Lively pose.",
    use: "Inventory, food, cooking input",
    theme: "bare_hands",
    category: "shellfish",
    chain: "crab",
    chainRole: "base",
    size: 64,
    tags: ["phase0", "beach", "food_raw", "gatherable"],
  },
  {
    id: "cooked_crab",
    object: "Cooked crab",
    description: "The SAME crab, now bright red-orange from cooking. Same pose but cooked color. Slight steam. Shell cracked slightly.",
    use: "Inventory, food",
    theme: "fire",
    category: "shellfish",
    chain: "crab",
    chainRole: "derived",
    chainNote: "Same crab turned bright red from cooking, shell slightly cracked",
    size: 64,
    tags: ["phase1b", "food_cooked", "fire"],
  },

  // ── Shell chain ───────────────────────────────────────────────────
  {
    id: "shell",
    object: "Small spiral seashell",
    description: "A small conch-type spiral shell, peach-pink with white highlights. Smooth, polished by waves.",
    use: "Inventory, crafting material",
    theme: "bare_hands",
    category: "shell",
    chain: "shell",
    chainRole: "base",
    size: 64,
    tags: ["phase0", "beach", "mineral", "gatherable"],
  },
  {
    id: "large_shell",
    object: "Large conch shell",
    description: "A big conch shell, same spiral type as shell but much larger. Deep pink interior visible. Impressive, trophy-like.",
    use: "Inventory, adze crafting",
    theme: "bare_hands",
    category: "shell",
    chain: "shell",
    chainRole: "derived",
    chainNote: "Same shell species, scaled up significantly — show the pink interior",
    size: 64,
    tags: ["phase1", "beach", "mineral"],
  },

  // ── Bamboo chain ──────────────────────────────────────────────────
  {
    id: "bamboo_cane",
    object: "Whole bamboo stalk section",
    description: "A green bamboo cane segment with visible nodes/joints. Fresh-cut, bright green with pale yellow at the nodes.",
    use: "Inventory, bamboo crafting base",
    theme: "bamboo",
    category: "bamboo",
    chain: "bamboo",
    chainRole: "base",
    size: 64,
    tags: ["phase1", "bamboo_grove", "organic", "gatherable"],
  },
  {
    id: "bamboo_splinter",
    object: "Split bamboo strip",
    description: "A thin, sharp bamboo splinter/strip. Same green color as bamboo_cane. Pale interior visible, sharp edge.",
    use: "Inventory, tool/crafting component",
    theme: "bamboo",
    category: "bamboo",
    chain: "bamboo",
    chainRole: "derived",
    chainNote: "A thin strip split from the bamboo cane — same color, sharper",
    size: 64,
    tags: ["phase1", "organic", "craftable"],
  },

  // ── Farming chains ────────────────────────────────────────────────
  {
    id: "wild_seed",
    object: "Small wild plant seeds",
    description: "A few small brown seeds in an open palm-leaf pouch. Earthy, organic look. Various sizes.",
    use: "Inventory, farming input",
    theme: "bamboo",
    category: "seed",
    chain: null,
    chainRole: "standalone",
    size: 64,
    tags: ["farming", "organic"],
  },
  {
    id: "root_vegetable",
    object: "Rough root vegetable",
    description: "A knobby brown root, freshly dug — dirt still clinging. Similar to a wild yam. Earthy brown.",
    use: "Inventory, food, cooking input",
    theme: "bamboo",
    category: "root",
    chain: "root_veg",
    chainRole: "base",
    size: 64,
    tags: ["farming", "food_raw", "organic"],
  },
  {
    id: "cooked_root_vegetable",
    object: "Roasted root vegetable",
    description: "Same root vegetable, now split open showing golden-orange cooked interior. Char marks on skin, steaming.",
    use: "Inventory, food",
    theme: "fire",
    category: "root",
    chain: "root_veg",
    chainRole: "derived",
    chainNote: "Same root, split open and roasted — golden interior, charred skin",
    size: 64,
    tags: ["farming", "food_cooked", "fire"],
  },
  {
    id: "taro_corm",
    object: "Taro corm (unplanted)",
    description: "A small purple-brown taro corm with stubby roots. Compact, bulb-like. Distinctive purple tinge.",
    use: "Inventory, farming plantable",
    theme: "bamboo",
    category: "root",
    chain: "taro",
    chainRole: "base",
    size: 64,
    tags: ["farming", "organic"],
  },
  {
    id: "taro_root",
    object: "Harvested taro root",
    description: "Large taro root, same purple-brown as taro_corm but bigger. Cross-section would show white-purple interior. Freshly harvested.",
    use: "Inventory, food, cooking input",
    theme: "bamboo",
    category: "root",
    chain: "taro",
    chainRole: "derived",
    chainNote: "Grown version of the corm — same purple-brown, much larger",
    size: 64,
    tags: ["farming", "food_raw", "organic"],
  },
  {
    id: "cooked_taro",
    object: "Cooked taro",
    description: "Taro root sliced and cooked, showing creamy purple-white interior. On a leaf plate. Light steam.",
    use: "Inventory, food",
    theme: "fire",
    category: "root",
    chain: "taro",
    chainRole: "derived",
    chainNote: "Same taro root, now sliced and cooked — show the purple-white flesh",
    size: 64,
    tags: ["farming", "food_cooked", "fire"],
  },
  {
    id: "banana_shoot",
    object: "Banana plant sucker/shoot",
    description: "A small banana plant shoot with a couple of unfurling leaves. Bright green, fresh, compact.",
    use: "Inventory, farming plantable",
    theme: "bamboo",
    category: "fruit",
    chain: "banana",
    chainRole: "base",
    size: 64,
    tags: ["farming", "organic"],
  },
  {
    id: "banana",
    object: "Ripe banana bunch",
    description: "A small hand of 3-4 bright yellow bananas. Tropical, cheerful. Classic banana shape and color.",
    use: "Inventory, food",
    theme: "bamboo",
    category: "fruit",
    chain: "banana",
    chainRole: "derived",
    chainNote: "The fruit produced by the shoot — bright yellow bananas",
    size: 64,
    tags: ["farming", "food_raw", "organic"],
  },
  {
    id: "breadfruit_cutting",
    object: "Breadfruit stem cutting",
    description: "A short woody stem cutting with a few broad leaves. Dark green leaves, brown stem with root nubs.",
    use: "Inventory, farming plantable",
    theme: "bamboo",
    category: "fruit",
    chain: "breadfruit",
    chainRole: "base",
    size: 64,
    tags: ["farming", "organic"],
  },
  {
    id: "breadfruit",
    object: "Whole breadfruit",
    description: "A round, bumpy-skinned green breadfruit. Tennis-ball sized, distinctive pebbled texture. Light green.",
    use: "Inventory, food, cooking input",
    theme: "bamboo",
    category: "fruit",
    chain: "breadfruit",
    chainRole: "derived",
    chainNote: "The fruit grown from the cutting — round, bumpy green",
    size: 64,
    tags: ["farming", "food_raw", "organic"],
  },
  {
    id: "roasted_breadfruit",
    object: "Roasted breadfruit",
    description: "Same breadfruit, now charred on outside, split open to show fluffy golden interior like bread. Steam rising.",
    use: "Inventory, food",
    theme: "fire",
    category: "fruit",
    chain: "breadfruit",
    chainRole: "derived",
    chainNote: "Same breadfruit, fire-roasted — blackened skin, golden bread-like interior",
    size: 64,
    tags: ["farming", "food_cooked", "fire"],
  },

  // ── Clay chain ────────────────────────────────────────────────────
  {
    id: "clay",
    object: "Lump of wet clay",
    description: "A moist reddish-brown clay lump, slightly glistening. Finger marks visible. Earthy, muddy.",
    use: "Inventory, pottery input",
    theme: "bare_hands",
    category: "clay",
    chain: "pottery",
    chainRole: "base",
    size: 64,
    tags: ["phase2", "jungle", "mineral"],
  },
  {
    id: "shaped_clay_pot",
    object: "Unfired clay pot",
    description: "A small coil-built pot, same reddish clay color. Still wet-looking, rough texture, slightly lopsided — handmade feel.",
    use: "Inventory, pottery intermediate",
    theme: "bare_hands",
    category: "clay",
    chain: "pottery",
    chainRole: "derived",
    chainNote: "Same clay, now shaped into a pot — wet, rough, handmade",
    size: 64,
    tags: ["phase2", "crafted", "mineral"],
  },

  // ─────────────────────────────────────────────────────────────────
  // TODO: Add remaining icons from the full spec as the game grows:
  // - fired_clay_pot (pottery chain, derived)
  // - Tools (hand_axe, bamboo_knife, stone_adze, fishing_spear, etc.)
  // - Structures (lean_to, fire_pit, drying_rack, etc.)
  // - Navigation (compass, map, sail, etc.)
  // - More farming outputs, cooked variants
  // ─────────────────────────────────────────────────────────────────
];
